### ISSUE TITLE
Hardhat: SonarCloud Config

### ISSUE THREAD

**Issue by nwbrettski** [vechainfoundation/hardhat-plugins#12]
Add the following repos to sonarcloud

- [x] https://github.com/vechainfoundation/hardhat-plugin
- [x] https://github.com/vechainfoundation/hardhat-plugin-sample-web3
- [x] https://github.com/vechainfoundation/hardhat-plugin-sample-ethers

**Comment by vanja-vechain** [comment]
https://sonarcloud.io/summary/new_code?id=vechainfoundation_hardhat-plugin-sample-web3&pullRequest=3
