### ISSUE TITLE
bug(tests): revertedWith not working when using vechain network 

### ISSUE THREAD

**Issue by akanoce** [vechainfoundation/hardhat-plugins#30]
When testing contracts using a vechain network `revertedWith` does not work, making it not possible to test the revert reason of a function call. `reverted` work as expected

The same does not occur when using hardhat network

### This works 

`await expect(contract.function()).to.be.reverted`

### This doesn't 

`await expect(contract.function()).to.be.revertedWith("permission denied")`

![Screenshot 2023-07-04 at 11 12 55](https://github.com/vechainfoundation/hardhat-plugins/assets/15635248/98eb97d6-476d-4704-ba28-356f3c08fcf5)

Happy to provide additional info if needed

**Comment by akanoce** [comment]
Thanks for the feedback @vanja-vechain 
This is a bit weird as that syntax does not work with the eth/hardhat network.
Isn't it possible to have this work as expected ? 
```
await expect(contract.function()).to.be.revertedWith("permission denied"
```

**Comment by vanja-vechain** [comment]
This is related to https://ethereum.stackexchange.com/questions/134884/revertedwith-not-matched-error-message
