### ISSUE TITLE
bug(tests): vechain-ethers plugin requires hardhat-vechain on 0.1.2

### ISSUE THREAD

**Issue by akanoce** [vechainfoundation/hardhat-plugins#31]
When running `npx hardhat test` or `npx hardhat coverage` i receive the error below

![Screenshot 2023-07-04 at 14 11 25](https://github.com/vechainfoundation/hardhat-plugins/assets/15635248/8b9a07f5-8844-49f2-808b-19205666679e)

The same does not happen when running `0.0.3`

NB: This is when using hardhat network. No errors with vechain's one

**Comment by vanja-vechain** [comment]
Hi @akanoce , yes based on the changes introduced in https://github.com/vechainfoundation/hardhat-plugins/issues/13 only vechain networks are supported.

**Comment by akanoce** [comment]
Hey @vanja-vechain thanks for the response.
Actually , I don't think this is solved. 
Not having the possibility to use hardhat-network for testing purposes, is very limiting and would possibly prevent users adopting this plugin. The reason is soon said: Testing with the latter network, is very quick. Unfortunately we cannot say the same when testing against a real node (deploying a simple contract on solo takes more than 10s) which comes with additional limitations like [https://github.com/vechainfoundation/hardhat-plugins/issues/30](https://github.com/vechainfoundation/hardhat-plugins/issues/30)
