### ISSUE TITLE
Add support for fee delegation

### ISSUE THREAD

**Issue by ifavo** [vechainfoundation/hardhat-plugins#5]
The previous hardhat plugins https://github.com/zzGHzz/hardhat-thor-plugin and https://gitlab.com/vechain.energy/common/hardhat-thor supported fee delegation.

The new one seems to either not support it or the usage is not documented.

Adding or documenting this feature would allow more developers to move to the new official plugins.

**Comment by nwbrettski** [comment]
Hey @ifavo,

Fee delegation is now possible in the plugin and the readme has been updated to include a sample `hardhat.config.js` with fee delegation.

Latest release available here: https://www.npmjs.com/package/@vechain/hardhat-vechain
