### ISSUE TITLE
Hardhat: Support Network Names

### ISSUE THREAD

**Issue by nwbrettski** [vechainfoundation/hardhat-plugins#9]
As raised in this issue, https://github.com/vechainfoundation/hardhat-plugins/issues/6, the user should be able to provide different network names. The issue raises an example of being able to provide a `testnet` network name and configuration but shows that this causes a failure in the plugin.

Acceptance Criteria:

- [x] A user should be able to provide any network name in the configuration for `hardhat-web3`
- [x] A user should be able to provide any network name in the configuration for `hardhat-ethers`
- [x] Manual testing `hardhat-web3` config change.
- [x] Manual testing `hardhat-ethers` config change.
- [ ] Update hardhat-plugins-sample-web3 (https://github.com/vechainfoundation/hardhat-plugin-sample-web3)
- [ ] Update hardhat-plugins-sample-ethers (https://github.com/vechainfoundation/hardhat-plugin-sample-ethers)

**Comment by vanja-vechain** [comment]
As discussed offline, fix now allows multiple vechain networks with ```vechain``` in the name. Update of the sample project will be done once the plugin is released
